#!/usr/bin/env python3
"""
Generate Design Tokens from a Brand Specification.

Outputs:
1. tokens.json (W3C Design Token Community Group format)
2. brand-tokens.css (CSS Custom Properties for light and dark modes)
3. tailwind.brand.js (Tailwind CSS configuration preset)

Includes WCAG 2.1 contrast ratio calculations and validation warnings.
"""

import argparse
import json
import math
import os
import sys
from typing import Dict, Any, Tuple, List


def hex_to_rgb(hex_str: str) -> Tuple[int, int, int]:
    """Convert hex color string to (R, G, B) tuple."""
    hex_str = hex_str.strip().lstrip("#")
    if len(hex_str) == 3:
        hex_str = "".join([c * 2 for c in hex_str])
    if len(hex_str) != 6:
        raise ValueError(f"Invalid hex color: {hex_str}")
    return int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16)


def rgb_to_hex(r: float, g: float, b: float) -> str:
    """Convert RGB float/int tuple to #RRGGBB string."""
    ir = max(0, min(255, int(round(r))))
    ig = max(0, min(255, int(round(g))))
    ib = max(0, min(255, int(round(b))))
    return f"#{ir:02x}{ig:02x}{ib:02x}"


def relative_luminance(r: int, g: int, b: int) -> float:
    """Calculate relative luminance per WCAG 2.1 definition."""

    def channel_lum(val: int) -> float:
        s = val / 255.0
        return s / 12.92 if s <= 0.03928 else math.pow((s + 0.055) / 1.055, 2.4)

    return 0.2126 * channel_lum(r) + 0.7152 * channel_lum(g) + 0.0722 * channel_lum(b)


def contrast_ratio(hex1: str, hex2: str) -> float:
    """Calculate WCAG 2.1 contrast ratio between two hex colors."""
    lum1 = relative_luminance(*hex_to_rgb(hex1))
    lum2 = relative_luminance(*hex_to_rgb(hex2))
    lighter = max(lum1, lum2)
    darker = min(lum1, lum2)
    return (lighter + 0.05) / (darker + 0.05)


def generate_color_scale(base_hex: str) -> Dict[str, str]:
    """
    Generate a 10-step tonal scale (50, 100, 200, ..., 900, 950) around a base color.
    Uses perceptual lightness blending toward white (#FFFFFF) and dark slate (#090D16).
    """
    r, g, b = hex_to_rgb(base_hex)
    scale = {}

    steps = {
        "50": 0.92,
        "100": 0.82,
        "200": 0.65,
        "300": 0.45,
        "400": 0.22,
        "500": 0.0,  # Base color
        "600": -0.15,
        "700": -0.32,
        "800": -0.48,
        "900": -0.65,
        "950": -0.80,
    }

    for step, shift in steps.items():
        if shift > 0:
            # Blend toward pure white
            nr = r + (255 - r) * shift
            ng = g + (255 - g) * shift
            nb = b + (255 - b) * shift
        elif shift < 0:
            # Blend toward deep tint
            dark_target = (10, 15, 26)
            factor = abs(shift)
            nr = r + (dark_target[0] - r) * factor
            ng = g + (dark_target[1] - g) * factor
            nb = b + (dark_target[2] - b) * factor
        else:
            nr, ng, nb = r, g, b

        scale[step] = rgb_to_hex(nr, ng, nb)

    return scale


def build_w3c_tokens(brand_data: Dict[str, Any]) -> Dict[str, Any]:
    """Generate W3C Design Tokens Community Group specification structure."""
    tokens = {
        "$name": brand_data.get("name", "Brand Tokens"),
        "$description": "Design tokens generated by OpenCode branding-process skill",
        "color": {
            "brand": {},
            "neutral": {},
            "semantic": {
                "success": {
                    "$type": "color",
                    "$value": brand_data.get("success", "#10b981"),
                },
                "warning": {
                    "$type": "color",
                    "$value": brand_data.get("warning", "#f59e0b"),
                },
                "error": {
                    "$type": "color",
                    "$value": brand_data.get("error", "#ef4444"),
                },
                "info": {"$type": "color", "$value": brand_data.get("info", "#0ea5e9")},
            },
        },
        "fontFamily": {
            "display": {
                "$type": "fontFamily",
                "$value": brand_data.get("font_display", "Inter, sans-serif"),
            },
            "body": {
                "$type": "fontFamily",
                "$value": brand_data.get(
                    "font_body", "system-ui, -apple-system, sans-serif"
                ),
            },
            "mono": {
                "$type": "fontFamily",
                "$value": brand_data.get(
                    "font_mono", "ui-monospace, SFMono-Regular, Menlo, monospace"
                ),
            },
        },
        "borderRadius": {
            "sm": {"$type": "dimension", "$value": "4px"},
            "md": {"$type": "dimension", "$value": "8px"},
            "lg": {"$type": "dimension", "$value": "12px"},
            "xl": {"$type": "dimension", "$value": "16px"},
            "full": {"$type": "dimension", "$value": "9999px"},
        },
        "spacing": {
            "1": {"$type": "dimension", "$value": "4px"},
            "2": {"$type": "dimension", "$value": "8px"},
            "3": {"$type": "dimension", "$value": "12px"},
            "4": {"$type": "dimension", "$value": "16px"},
            "6": {"$type": "dimension", "$value": "24px"},
            "8": {"$type": "dimension", "$value": "32px"},
            "12": {"$type": "dimension", "$value": "48px"},
            "16": {"$type": "dimension", "$value": "64px"},
        },
    }

    # Primary brand palette
    primary_scale = generate_color_scale(brand_data.get("primary", "#2563eb"))
    tokens["color"]["brand"]["primary"] = {
        step: {"$type": "color", "$value": hex_val}
        for step, hex_val in primary_scale.items()
    }
    tokens["color"]["brand"]["primary"]["DEFAULT"] = {
        "$type": "color",
        "$value": brand_data.get("primary", "#2563eb"),
    }

    # Secondary brand palette if provided
    if "secondary" in brand_data:
        sec_scale = generate_color_scale(brand_data["secondary"])
        tokens["color"]["brand"]["secondary"] = {
            step: {"$type": "color", "$value": hex_val}
            for step, hex_val in sec_scale.items()
        }
        tokens["color"]["brand"]["secondary"]["DEFAULT"] = {
            "$type": "color",
            "$value": brand_data["secondary"],
        }

    # Accent color if provided
    if "accent" in brand_data:
        acc_scale = generate_color_scale(brand_data["accent"])
        tokens["color"]["brand"]["accent"] = {
            step: {"$type": "color", "$value": hex_val}
            for step, hex_val in acc_scale.items()
        }
        tokens["color"]["brand"]["accent"]["DEFAULT"] = {
            "$type": "color",
            "$value": brand_data["accent"],
        }

    # Neutral scale
    neutral_scale = generate_color_scale(brand_data.get("neutral", "#64748b"))
    tokens["color"]["neutral"] = {
        step: {"$type": "color", "$value": hex_val}
        for step, hex_val in neutral_scale.items()
    }

    return tokens


def build_css_variables(brand_data: Dict[str, Any], tokens: Dict[str, Any]) -> str:
    """Generate CSS Custom Properties with light and dark mode variable sets."""
    primary_scale = generate_color_scale(brand_data.get("primary", "#2563eb"))
    neutral_scale = generate_color_scale(brand_data.get("neutral", "#64748b"))

    lines = [
        "/* =====================================================================",
        f" * Brand Design Tokens: {brand_data.get('name', 'Brand')}",
        " * Generated by OpenCode branding-process skill",
        " * ===================================================================== */",
        "",
        ":root {",
        "  /* Typography */",
        f"  --brand-font-display: {brand_data.get('font_display', 'Inter, sans-serif')};",
        f"  --brand-font-body: {brand_data.get('font_body', 'system-ui, -apple-system, sans-serif')};",
        f"  --brand-font-mono: {brand_data.get('font_mono', 'ui-monospace, monospace')};",
        "",
        "  /* Primary Brand Scale */",
    ]

    for step, val in primary_scale.items():
        lines.append(f"  --brand-primary-{step}: {val};")
    lines.append(f"  --brand-primary: var(--brand-primary-500);")
    lines.append("")

    if "secondary" in brand_data:
        sec_scale = generate_color_scale(brand_data["secondary"])
        lines.append("  /* Secondary Brand Scale */")
        for step, val in sec_scale.items():
            lines.append(f"  --brand-secondary-{step}: {val};")
        lines.append(f"  --brand-secondary: var(--brand-secondary-500);")
        lines.append("")

    if "accent" in brand_data:
        acc_scale = generate_color_scale(brand_data["accent"])
        lines.append("  /* Accent Scale */")
        for step, val in acc_scale.items():
            lines.append(f"  --brand-accent-{step}: {val};")
        lines.append(f"  --brand-accent: var(--brand-accent-500);")
        lines.append("")

    lines.append("  /* Neutral Scale */")
    for step, val in neutral_scale.items():
        lines.append(f"  --brand-neutral-{step}: {val};")
    lines.append("")

    lines.extend(
        [
            "  /* Semantic Tokens */",
            f"  --brand-success: {brand_data.get('success', '#10b981')};",
            f"  --brand-warning: {brand_data.get('warning', '#f59e0b')};",
            f"  --brand-error: {brand_data.get('error', '#ef4444')};",
            f"  --brand-info: {brand_data.get('info', '#0ea5e9')};",
            "",
            "  /* Surface & Text Tokens (Light Mode Default) */",
            "  --surface-canvas: #ffffff;",
            "  --surface-raised: #f8fafc;",
            "  --surface-card: #ffffff;",
            "  --surface-overlay: rgba(15, 23, 42, 0.04);",
            "  --border-subtle: var(--brand-neutral-200);",
            "  --border-strong: var(--brand-neutral-300);",
            "  --text-primary: var(--brand-neutral-900);",
            "  --text-secondary: var(--brand-neutral-600);",
            "  --text-muted: var(--brand-neutral-400);",
            "  --text-on-brand: #ffffff;",
            "}",
            "",
            "/* Dark Mode Overrides */",
            '[data-theme="dark"],',
            "@media (prefers-color-scheme: dark) {",
            "  :root {",
            "    --surface-canvas: #090d16;",
            "    --surface-raised: #0f172a;",
            "    --surface-card: #131d33;",
            "    --surface-overlay: rgba(255, 255, 255, 0.04);",
            "    --border-subtle: #1e293b;",
            "    --border-strong: #334155;",
            "    --text-primary: #f8fafc;",
            "    --text-secondary: #94a3b8;",
            "    --text-muted: #64748b;",
            "    --text-on-brand: #ffffff;",
            "  }",
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def build_tailwind_preset(brand_data: Dict[str, Any]) -> str:
    """Generate Tailwind CSS configuration preset."""
    primary_scale = generate_color_scale(brand_data.get("primary", "#2563eb"))
    neutral_scale = generate_color_scale(brand_data.get("neutral", "#64748b"))

    sec_scale = (
        generate_color_scale(brand_data["secondary"])
        if "secondary" in brand_data
        else None
    )
    acc_scale = (
        generate_color_scale(brand_data["accent"]) if "accent" in brand_data else None
    )

    code = [
        "/**",
        f" * Tailwind CSS Preset for {brand_data.get('name', 'Brand')}",
        " * Generated by OpenCode branding-process skill",
        " */",
        "module.exports = {",
        "  theme: {",
        "    extend: {",
        "      colors: {",
        "        brand: {",
        "          DEFAULT: 'var(--brand-primary)',",
    ]

    for step, val in primary_scale.items():
        code.append(f"          {step}: '{val}',")
    code.append("        },")

    if sec_scale:
        code.append("        secondary: {")
        code.append("          DEFAULT: 'var(--brand-secondary)',")
        for step, val in sec_scale.items():
            code.append(f"          {step}: '{val}',")
        code.append("        },")

    if acc_scale:
        code.append("        accent: {")
        code.append("          DEFAULT: 'var(--brand-accent)',")
        for step, val in acc_scale.items():
            code.append(f"          {step}: '{val}',")
        code.append("        },")

    code.append("        neutral: {")
    for step, val in neutral_scale.items():
        code.append(f"          {step}: '{val}',")
    code.append("        },")

    code.extend(
        [
            "        surface: {",
            "          canvas: 'var(--surface-canvas)',",
            "          raised: 'var(--surface-raised)',",
            "          card: 'var(--surface-card)',",
            "        },",
            "        content: {",
            "          primary: 'var(--text-primary)',",
            "          secondary: 'var(--text-secondary)',",
            "          muted: 'var(--text-muted)',",
            "          'on-brand': 'var(--text-on-brand)',",
            "        },",
            "      },",
            "      fontFamily: {",
            f"        display: ['{brand_data.get('font_display', 'Inter')}', 'sans-serif'],",
            f"        body: ['{brand_data.get('font_body', 'system-ui')}', 'sans-serif'],",
            f"        mono: ['{brand_data.get('font_mono', 'monospace')}'],",
            "      },",
            "    },",
            "  },",
            "};",
            "",
        ]
    )

    return "\n".join(code)


def validate_brand_contrast(brand_data: Dict[str, Any]) -> List[str]:
    """Validate key color combinations against WCAG 2.1 AA (4.5:1 / 3:1) standards."""
    warnings = []
    primary = brand_data.get("primary", "#2563eb")

    # White on primary
    cr_white_on_primary = contrast_ratio("#ffffff", primary)
    if cr_white_on_primary < 4.5:
        warnings.append(
            f"WCAG Warning: White (#ffffff) on Primary ({primary}) contrast ratio is {cr_white_on_primary:.2f}:1 "
            f"(fails AA normal text threshold of 4.5:1; passes large text 3:1 if >= 3.0)."
        )

    # Primary on white canvas
    cr_primary_on_white = contrast_ratio(primary, "#ffffff")
    if cr_primary_on_white < 4.5:
        warnings.append(
            f"WCAG Warning: Primary ({primary}) text on White background contrast ratio is {cr_primary_on_white:.2f}:1 "
            f"(recommend using primary-600 or primary-700 for small body text)."
        )

    return warnings


def main():
    parser = argparse.ArgumentParser(
        description="Generate design tokens from brand parameters."
    )
    parser.add_argument("--config", help="Path to brand.json configuration file")
    parser.add_argument("--name", default="Brand", help="Brand name")
    parser.add_argument(
        "--primary", default="#2563eb", help="Primary brand color (hex)"
    )
    parser.add_argument("--secondary", default="#10b981", help="Secondary color (hex)")
    parser.add_argument("--accent", default="#8b5cf6", help="Accent color (hex)")
    parser.add_argument(
        "--neutral", default="#64748b", help="Neutral slate color (hex)"
    )
    parser.add_argument(
        "--font-display", default="Inter, sans-serif", help="Display font family"
    )
    parser.add_argument(
        "--font-body", default="system-ui, sans-serif", help="Body font family"
    )
    parser.add_argument(
        "--out-dir", default="./brand-assets/tokens", help="Output directory"
    )

    args = parser.parse_args()

    if args.config and os.path.exists(args.config):
        with open(args.config, "r", encoding="utf-8") as f:
            brand_data = json.load(f)
    else:
        brand_data = {
            "name": args.name,
            "primary": args.primary,
            "secondary": args.secondary,
            "accent": args.accent,
            "neutral": args.neutral,
            "font_display": args.font_display,
            "font_body": args.font_body,
        }

    os.makedirs(args.out_dir, exist_ok=True)

    # 1. W3C Tokens JSON
    tokens = build_w3c_tokens(brand_data)
    tokens_path = os.path.join(args.out_dir, "tokens.json")
    with open(tokens_path, "w", encoding="utf-8") as f:
        json.dump(tokens, f, indent=2)

    # 2. CSS Custom Properties
    css_content = build_css_variables(brand_data, tokens)
    css_path = os.path.join(args.out_dir, "brand-tokens.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css_content)

    # 3. Tailwind Preset
    tailwind_content = build_tailwind_preset(brand_data)
    tw_path = os.path.join(args.out_dir, "tailwind.brand.js")
    with open(tw_path, "w", encoding="utf-8") as f:
        f.write(tailwind_content)

    # Contrast evaluation
    warnings = validate_brand_contrast(brand_data)

    print(f"Successfully generated brand design tokens in '{args.out_dir}':")
    print(f"  - W3C Tokens: {tokens_path}")
    print(f"  - CSS Variables: {css_path}")
    print(f"  - Tailwind Preset: {tw_path}")

    if warnings:
        print("\nAccessibility Warnings:")
        for w in warnings:
            print(f"  ! {w}")
    else:
        print(
            "\nAccessibility Check: All primary contrast pairings meet WCAG AA standards."
        )


if __name__ == "__main__":
    main()
